# Version of docker-compose.
version: '3.9'

volumes:
  pgdata:

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: mix phx.server
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: cargapesada
      PGPORT: 5432
      PGHOST: db
      SECRET_KEY: 4dwbfD074O1NTSuNyIPT8YzLWvh8FUqj/nBdPIzWGbDUhN7WuFKy/smtO/7wrvRL
    ports:
      - '4000:4000'
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
